"""schema inicial

Revision ID: a2c11a78f505
Revises: 
Create Date: 2026-08-18 16:07:45.787214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2c11a78f505'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('tickio_sistema_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repo')),
    sa.UniqueConstraint('nome', name=op.f('uq_repo_nome'))
    )
    op.create_table('exclusao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('hash_origem', sa.String(), nullable=False),
    sa.Column('versao_numero', sa.String(), nullable=True),
    sa.Column('motivo', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repo.id'], name=op.f('fk_exclusao_repo_id_repo')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exclusao'))
    )
    op.create_index('uq_exclusao_repo_hash_versao', 'exclusao', ['repo_id', 'hash_origem', sa.literal_column("coalesce(versao_numero, '')")], unique=True)
    op.create_table('repo_alias',
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repo.id'], name=op.f('fk_repo_alias_repo_id_repo')),
    sa.PrimaryKeyConstraint('nome', name=op.f('pk_repo_alias'))
    )
    op.create_table('sem_entrega',
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('chamado', sa.String(), nullable=False),
    sa.Column('motivo', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repo.id'], name=op.f('fk_sem_entrega_repo_id_repo')),
    sa.PrimaryKeyConstraint('repo_id', 'chamado', name=op.f('pk_sem_entrega'))
    )
    op.create_table('versao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('base_ref', sa.String(), nullable=False),
    sa.Column('base_commit', sa.String(), nullable=False),
    sa.Column('liberada_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repo.id'], name=op.f('fk_versao_repo_id_repo')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_versao')),
    sa.UniqueConstraint('repo_id', 'numero', name=op.f('uq_versao_repo_id'))
    )
    op.create_table('atribuicao',
    sa.Column('versao_id', sa.Integer(), nullable=False),
    sa.Column('chamado', sa.String(), nullable=False),
    sa.Column('marcada', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['versao_id'], ['versao.id'], name=op.f('fk_atribuicao_versao_id_versao')),
    sa.PrimaryKeyConstraint('versao_id', 'chamado', name=op.f('pk_atribuicao'))
    )
    op.create_table('atribuicao_commit',
    sa.Column('versao_id', sa.Integer(), nullable=False),
    sa.Column('chamado', sa.String(), nullable=False),
    sa.Column('hash_origem', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['versao_id', 'chamado'], ['atribuicao.versao_id', 'atribuicao.chamado'], name=op.f('fk_atribuicao_commit_versao_id_atribuicao'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('versao_id', 'chamado', 'hash_origem', name=op.f('pk_atribuicao_commit'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('atribuicao_commit')
    op.drop_table('atribuicao')
    op.drop_table('versao')
    op.drop_table('sem_entrega')
    op.drop_table('repo_alias')
    op.drop_index('uq_exclusao_repo_hash_versao', table_name='exclusao')
    op.drop_table('exclusao')
    op.drop_table('repo')
    # ### end Alembic commands ###
